# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://cmsilv.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""


# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Curt Silverthorn"
title: "Curt Silverthorn"
description: "Personal website and blog of Curt Silverthorn."
keywords: "Curt, Silverthorn, curt, silverthorn, bryant, personal, jekyll, theme"
favicon: "/img/personBlack.ico"

################
# Header layout #
################

black-favicon: "/img/personWhite.ico"

background-img: "../img/universe-background.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "If debugging is the process of removing software bugs, then programming must be the process of putting them in."
  - text: "Good design adds value faster than it adds cost."
  - text: "It’s not a bug – it’s an undocumented feature."
  - text: "Some people, when confronted with a problem, think, 'I know, I'll use threads' - and then two they hav erpoblesms."
  
# me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

me-img: "https://graph.facebook.com/100000053129514/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: ""
icon-48p: ""
icon-72p: ""
icon-96p: ""
icon-144p: ""
icon-192p: ""

############
# Timeline #
############

events:
  - image: "/img/timeline/advantagecs_logo.png"
    date: "Starting Summer 2018"
    description: "Software Developer at AdvantageCS"
  - image: "/img/timeline/wethepeople.png"
    date: "September 2017 - December 2017"
    description: "Created \"WeThePeople\" A Legislative News Feed Mobile App For EECS 441"
  - image: "/img/timeline/Dell_Logo.png"
    date: "June 2017 - August 2017"
    description: "CTO Software Architecture Intern at Dell"
  - image: "/img/timeline/fca_logo.png"
    date: "May 2016 - August 2016"
    description: "SAP IT Intern at Fiat Chrysler Automobiles"
  - image: "/img/timeline/tecnun.jpeg"
    date: "May 2015 - June 2015"
    description: "Studied Abroad at The University of Nevarra in Spain"
  - image: "/img/timeline/maav.jpeg"
    date: "October 2014"
    description: "Joined the Michigan Autonomous Aerial Vehicle Student Design Team \"MAAV\""
  - image: "/img/timeline/umich_seal.png"
    date: "September 2014"
    description: "Started School at the University of Michigan"
  - image: "/img/timeline/claymore.jpg"
    date: "September 2013 - April 2014"
    description: "Built a Motion-Activated Airsoft Claymore"

# First image of the Timeline

timeline-img: "/img/timeline/michigan.jpeg"

###########
# Contact #
###########

email: "cmsilv@umich.edu"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/cmsilv"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/curt-silverthorn-bb3079126/"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Skills: 'skills'
  Courses: 'courses'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
